var stateCollection = {
    al: {
        "header": "Alabama",
        "body": "The new legislation, Senate Bill 226, was sponsored by Republican Senator Arthur Orr at the beginning of February 2016. And within a few months, the bill passed on May 4th, 2016. Then, a few days later, on May 10th, 2016, Alabama State Governor Robert Bentley signed the legislation into law. The bill itself states: “New synthetic substances are being created which are not controlled under the provisions of existing state law but which have a potential for abuse similar to or greater than that for substances controlled under existing state law. These new synthetic substances are called ‘synthetic controlled substances or synthetic controlled substance analogues’ and can be designed to produce a desired pharmacological effect and to evade the controlling statutory provisions. Synthetic controlled substances or synthetic controlled substance analogues are being manufactured, distributed, possessed, and used as substitutes for controlled substances.” And it goes on to list mitragynine and hydroxymitragynine (sic) within the bill for synthetic substances. However, neither mitragynine nor 7-hydroxymitragynine is a synthetic compound. Both are naturally occurring alkaloids found in the kratom plant. Still, even though kratom compounds are not synthetic, the state law continues to view kratom products and the plant as an illegal substance in Alabama at this time. The addition of both molecules added onto the bill cements the ban.",
        "link": "https://trackbill.com/bill/alabama-senate-bill-226-controlled-substances-additional-compounds-included-in-schedule-i-based-on-chemical-names-known-as-kratom-sec-20-2-23-amd/1263491/"
    },
    ar: {
        "header": "Arkansas",
        "body": "The Arkansas Department of Health was notified by Dr. Thomas Atkinson, M.D., from the Springdale Treatment Center in Springdale, AR, that patients at the addiction treatment center had used kratom before. He informed the Department of Health that kratom exhibits an opiate agonist action in subjects. He issued a warning about kratom because he believed the products shouldn’t be available to get bought by Arkansas citizens at local businesses. After hearing the doctor’s argument, the health department decided to take the matter into its own hands. Both mitragynine and 7-hydroxymitragynine were placed as a scheduled I narcotic on Arkansas’s List of Controlled Substances. You can find both alkaloids listed under Article II—Schedule I—(c) Opium Derivatives. The two compounds were The Department of Health’s Center for Health Protection held a public hearing on September 1st, 2015, where public comments were allowed on the subject. But when the comment period had expired, the Department of Health did not receive any public comments on the topic. So, the proposed bill went into effect on February 1st, 2016.",
        "link": "https://www.pharmacyboard.arkansas.gov/wp-content/uploads/2020/04/controlled_substances_list.pdf"
    },
}

export default stateCollection;